### ISSUE TITLE
Unable to get property 'getInstance' of undefined or null reference

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-ui#153] opened 2019-02-25 15:15 UTC
# Issue Description

Seeing 'Unable to get property 'getInstance' of undefined or null reference' in New Relic logs.  This error is happening in react-onclickoutside.  Likely one of our examples is causing this.  It only seems to be showing up in IE10 and IE11.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Environment

* Browser Name and Version: IE 10 and 11
* Operating System and version (desktop or mobile): Desktop

**Comment by bjankord** [comment] 2019-03-01 17:05
Steps to reproduce:

* Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-form-select/form-select/select in IE 11
* Click on the select to open it
* Click on the caret icon in the select to close it
* console error is logged `Unable to get property 'getInstance' of undefined or null reference`

**Comment by agivens96** [comment] 2019-03-01 17:19
Based on some investigation, the error occurs inside terra-hookshot which terra-form-select is consuming in [_Dropdown.jsx](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/_Dropdown.jsx#L3).

I did some testing and it looks like passing an onOutsideClick prop to Hookshot.Content will keep the react-onoutsideclick default methods from firing. This prevents the error and terra-form-select still functions as it did before since it has it's own onBlur event methods.

**Closed** 2019-03-06 18:20 UTC
Labels: Needs more info, bug, new relic
